---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  namespace: default
spec:
  selector:
    matchLabels:
      app: nodejs
      deployer: jenkins
  template:
    metadata:
      labels:
        app: nodejs
        deployer: jenkins
    spec:
      imagePullSecrets: 
      - name: icr-pull
      containers:
      - name: nodejs
        image: de.icr.io/volaka/application
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs
  labels:
    app: nodejs
    deployer: jenkins
spec:
  type: NodePort
  selector:
    app: nodejs
    deployer: jenkins
  ports:
  - port: 80
    targetPort: http
